# .gitlab-ci.yml
---
default:
  image: ogo.jfrog.io/default-docker-local/pipelinecomponents/ansible-lint:latest
  
stages:
  - ansible-lint
  - ansible-syntax-check


ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint loop_count.yml

ansible-syntax-check:
  stage: ansible-syntax-check
  script:
    - ansible-playbook --inventory inventory --syntax-check loop_count.yml
  #  - ansible-playbook  --syntax-check loop_count.yml

