# .gitlab-ci.yml
---

default:
  image: fogo.jfrog.io/default-docker-local/pipelinecomponents/ansible-lint:latest

  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
stages:
  - ansible-lint
  - ansible-syntax-check


ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint loop_count.yml

ansible-syntax-check:
  stage: ansible-syntax-check
  script:
    - ansible-playbook --inventory inventory --syntax-check loop_count.yml
  #  - ansible-playbook  --syntax-check loop_count.yml

