# roles/fg_ubus01/tasks/01_update_packages.yml
---

- name: aktualisiere apt-get repo und cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600


- name: aktualisiere alle installierte packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
    
    