# roles/fg_ubus01/tasks/04_install_docker.yml
---

- name: Install docker-ce
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure docker.service.d dir exists.
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Ensure Docker is started and enabled at boot.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes


    