# roles/fg_ubus01/tasks/04_install_docker.yml
---

- name: Install docker-ce
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: present
    update_cache: yes